# Configuration documentation:
#Â   https://embarkstudios.github.io/cargo-deny/index.html

[advisories]
yanked = "deny"
ignore = []
git-fetch-with-cli = true

[licenses]

exceptions = [
    # We should probably NOT bundle CA certs but use the OS ones.
    { name = "webpki-roots", allow = ["MPL-2.0"] },
    { name = "openobserve", allow = ["AGPL-3.0"] },
    { name = "config", allow = ["AGPL-3.0"] },
    { name = "infra", allow = ["AGPL-3.0"] },
    { name = "ingester", allow = ["AGPL-3.0"] },
    { name = "wal", allow = ["AGPL-3.0"] },
    { name = "proto", allow = ["AGPL-3.0"] },
    { name = "report_server", allow = ["AGPL-3.0"] },
    { name = "arrayref", allow = ["BSD-2-Clause"] },
    { name = "mach", allow = ["BSD-2-Clause"] },
    { name = "fastdivide", allow = ["zlib-acknowledgement"] },
    { name = "foldhash", allow = ["Zlib"] },
    # These two are transitive deps of vrl via dep rustyline.
    # However, rustyline is needed only when we enable feature cli
    # which we haven't. Probably in Cargo.lock due to old code, need
    # to take a look and remove.
    { name = "clipboard-win", allow = ["BSL-1.0"] },
    { name = "error-code", allow = ["BSL-1.0"] },
    { name = "base16", allow = ["CC0-1.0"] },
    { name = "tiny-keccak", allow = ["CC0-1.0"] },
    { name = "quoted_printable", allow = ["0BSD"] },
    { name = "ring", allow = ["BSD-4-Clause", "OpenSSL"] },
    { name = "adler32", allow = ["Zlib"] },
    { name = "inferno", allow = ["CDDL-1.0"] },
]

allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MPL-2.0",
    "MIT",
    "BSD-3-Clause", # OSI + fsf free
    "Unicode-3.0", # OSI
    "ISC", # OSI + fsf free
    "BSL-1.0",
]

[[licenses.clarify]]
name = "ring"
expression = "BSD-4-Clause AND ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[sources.allow-org]
github = ["openobserve", "apache"]

[sources]
allow-git = ["https://github.com/mattsse/chromiumoxide"]
