[package]
name = "proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
datafusion.workspace = true
datafusion-proto.workspace = true
prost.workspace = true
prost-wkt-types.workspace = true
serde.workspace = true
serde_json.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
tokio.workspace = true

[build-dependencies]
prost-build = { version = "0.14.1" }
tonic-prost-build = { version = "0.14.1" }
