[package]
name = "proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
datafusion.workspace = true
datafusion-proto.workspace = true
prost.workspace = true
prost-wkt-types.workspace = true
serde.workspace = true
serde_json.workspace = true
tonic.workspace = true
tokio.workspace = true

[build-dependencies]
tonic-build = { version = "0.11", features = ["prost"] }
prost-build = "0.12"
