[advisories]
ignore = [
  "RUSTSEC-2023-0071", # from rsa, transitive dep of sqlx
  "RUSTSEC-2021-0139", # from ansi_term, transitive dep of vrl
  "RUSTSEC-2024-0370", # we need it even it is no longer maintained
  "RUSTSEC-2024-0384", # from instant, dep of parking_lot
  "RUSTSEC-2024-0388", # from derivative, dep of vrl
  "RUSTSEC-2024-0421", # from idna, transitive dep of vrl
  "RUSTSEC-2024-0436", # from paste, transitive dep of datafusion
  "RUSTSEC-2024-0437", # from protobuf, transitive dep of prometheus
  "RUSTSEC-2025-0020", # from poy3, transitive dep of datafusion-functions-json
  "RUSTSEC-2026-0001", # from rkyv, dep of rust_decimal
]
informational_warnings = ["unmaintained"] # warn for categories of informational advisories
